\hypertarget{classdjango_1_1core_1_1exceptions_1_1_synchronous_only_operation}{}\doxysection{django.\+core.\+exceptions.\+Synchronous\+Only\+Operation Class Reference}
\label{classdjango_1_1core_1_1exceptions_1_1_synchronous_only_operation}\index{django.core.exceptions.SynchronousOnlyOperation@{django.core.exceptions.SynchronousOnlyOperation}}


Inheritance diagram for django.\+core.\+exceptions.\+Synchronous\+Only\+Operation\+:
% FIG 0


Collaboration diagram for django.\+core.\+exceptions.\+Synchronous\+Only\+Operation\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}The user tried to call a sync-only function from an async context.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/\+Lib/site-\/packages/django/core/exceptions.\+py\end{DoxyCompactItemize}
